version: "3.1"
services:
  parsamaz-php:
    depends_on:
      - parsamaz-mysql
    volumes:
      - .:/app

  parsamaz-nginx:
    image: nginx:1.15-alpine
    container_name: parsamaz-nginx
    depends_on:
      - parsamaz-php
    volumes:
      - .:/app
      - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/tmp/nginx:/var/log/nginx
    ports:
      - 3400:80

  parsamaz-mysql:
    image: mysql:5.7
    container_name: parsamaz-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local

  parsamaz-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    container_name: parsamaz-phpmyadmin
    ports:
      - 3402:80